import {
  MdOutlinePerson,
  MdOutlineLocationOn,
  MdNumbers,
  MdOutlineTextSnippet,
  MdEmail,
  MdLocalPhone,
  MdLanguage,
  MdHourglassBottom,
  MdImage,
  MdOutlineSpatialAudioOff,
  MdDateRange,
  MdFilterList,
  MdOutlineStopCircle,
  MdOutlineSkipNext,
} from "react-icons/md";

export const serviceInputDefaultData = [
  {
    id: "name",
    name: "Name*",
    value: "",
    default: "Community Food Kitchen",
    required: true,
  },
  {
    id: "address",
    name: "Address*",
    value: "",
    default: "123 Main St, Anytown, USA",
    required: true,
  },
  {
    id: "zipcode",
    name: "Zip Code*",
    value: "",
    default: "12345",
    required: true,
  },
  {
    id: "description",
    name: "Description*",
    value: "",
    default: "Providing free meals to those in need",
    required: true,
  },
  {
    id: "email",
    name: "Email",
    value: "",
    default: "info@communityfoodkitchen.org",
    required: false,
  },
  {
    id: "phone",
    name: "Phone",
    value: "",
    default: "(555) 555-5555",
    required: false,
  },
  {
    id: "website",
    name: "Website*",
    value: "",
    default: "https://www.communityfoodkitchen.org",
    required: true,
  },
  {
    id: "hours",
    name: "Hours",
    value: "",
    default: "Monday - Friday: 11am - 2pm, Saturday: 12pm - 3pm",
    required: false,
  },
  {
    id: "logo",
    name: "Logo",
    value: "",
    default: "https://www.communityfoodkitchen.org/logo.png",
    required: false,
  },
  {
    id: "language",
    name: "Language",
    value: "",
    default: "English",
    required: false,
  },
  {
    id: "date_needed",
    name: "Date Needed",
    value: "",
    default: "As soon as possible",
    required: false,
  },
  {
    id: "services_offered",
    name: "Services Offered*",
    value: "",
    default: "Free meals, food pantry, nutrition counseling",
    required: true,
  },
  {
    id: "restrictions",
    name: "Restrictions",
    value: "",
    default: "None",
    required: false,
  },
  {
    id: "next_steps",
    name: "Next Steps*",
    value: "",
    default: "Call or email to schedule an appointment",
    required: true,
  },
];
export const serviceInputDefaultValues = {
  name: { default: "Community Food Kitchen", icon: MdOutlinePerson },
  address: { default: "123 Main St, Anytown, USA", icon: MdOutlineLocationOn },
  zipcode: { default: "12345", icon: MdNumbers },
  description: {
    default: "Providing free meals to those in need",
    icon: MdOutlineTextSnippet,
  },
  email: { default: "info@communityfoodkitchen.org", icon: MdEmail },
  phone: { default: "(555) 555-5555", icon: MdLocalPhone },
  website: {
    default: "https://www.communityfoodkitchen.org",
    icon: MdLanguage,
  },
  hours: {
    default: "Monday - Friday: 11am - 2pm, Saturday: 12pm - 3pm",
    icon: MdHourglassBottom,
  },
  logo: {
    default: "https://www.communityfoodkitchen.org/logo.png",
    icon: MdImage,
  },
  language: { default: "English", icon: MdOutlineSpatialAudioOff },
  date_needed: { default: "As soon as possible", icon: MdDateRange },
  services_offered: {
    default: "Free meals, food pantry, nutrition counseling",
    icon: MdFilterList,
  },
  restrictions: { default: "None", icon: MdOutlineStopCircle },
  next_steps: {
    default: "Call or email to schedule an appointment",
    icon: MdOutlineSkipNext,
  },
};

export const serviceNameInputDefault = {
  id: "default",
  text: "Select a Service",
};
